# Goldmark markdown renderer settings.

[markup.goldmark]
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = "github"
  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = false
    xhtml = false

[markup.highlight]
  style = "dracula"
  tabWidth = 2
  lineNos = false
  noClasses = false

[markup.tableOfContents]
  endLevel = 4
  ordered = false
  startLevel = 2
